FROM node:14.17.3 as build
WORKDIR /app
COPY package.json ./
RUN npm install -g npm@latest
RUN npm install --silent
COPY . .
RUN npm run build

FROM nginx:1.21.6-alpine
LABEL author='Pham Tien Duc <ducpt@miichisoft.net>'
WORKDIR /app
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]